const {chromium} = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
const fs = require('node:fs');
(async()=>{
 const browser=await chromium.launch({channel:'chrome',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.ATLAS_URL||'http://127.0.0.1:8873/');
 await page.waitForFunction(()=>document.getElementById('atlasCount')?.textContent.includes('4,838'));
 const folder=path.resolve('../qa');fs.mkdirSync(folder,{recursive:true});
 await page.screenshot({path:path.join(folder,'desktop.png')});
 await page.getByRole('button',{name:'Growing',exact:true}).click();
 assert.match(await page.locator('#atlasCount').textContent(),/4,797/);
 await page.selectOption('#atlasMetric','daily');
 await page.selectOption('#atlasCountry','GB');
 await page.locator('#atlasCI').check();
 const count=await page.locator('#atlasCount').textContent();console.log('filtered',count);
 await page.locator('#atlasCI').uncheck();await page.selectOption('#atlasCountry','');
 await page.getByRole('button',{name:'Dormant',exact:true}).click();
 await page.locator('#atlasSearch').fill('3958');
 await page.locator('#atlasResults button').first().click();
 assert.equal(await page.locator('#inspectorTitle').textContent(),'GCIN 3958');
 assert.match(await page.locator('#inspectorBody').textContent(),/0.755/);
 await page.screenshot({path:path.join(folder,'inspector.png')});
 const download=page.waitForEvent('download');await page.locator('#atlasDownload').click();assert.match((await download).suggestedFilename(),/dormant.csv/);
 const pixel=await page.evaluate(()=>{const c=document.getElementById('mapCanvas'),d=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let colored=0;for(let i=0;i<d.length;i+=4)if(Math.max(d[i],d[i+1],d[i+2])-Math.min(d[i],d[i+1],d[i+2])>60)colored++;return colored;});
 assert(pixel>100,'Map pixels are blank');console.log('colored pixels',pixel);
 await page.reload();await page.waitForSelector('#atlasCount');await page.waitForFunction(()=>document.getElementById('inspectorTitle')?.textContent==='GCIN 3958');
 await page.setViewportSize({width:390,height:844});await page.goto((process.env.ATLAS_URL||'http://127.0.0.1:8873/')+'?season=dormant&metric=type');
 await page.waitForFunction(()=>document.getElementById('atlasCount')?.textContent.includes('4,838'));
 await page.screenshot({path:path.join(folder,'mobile.png')});
 await page.locator('#btnShowPanel').click();await page.waitForTimeout(300);await page.screenshot({path:path.join(folder,'mobile-controls.png')});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 assert.deepEqual(errors,[]);console.log('PASS: counts, filters, inspector, downloads, URL state, canvas, mobile, runtime errors');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
